aruco_detector:
  ros__parameters:
    camera_module: hal_allied_vision_camera
    pose_topic_hz: 30
    #marker_side: 0.25
    marker_side: 0.07

    custom_marker_side_dict:
      enable: False

    publishers:
      marker_image: /target_tracking/marker_image
      marker_transform_prefix: /target_tracking/camera_to_marker_transform/marker_
      marker_presence_prefix: /target_tracking/camera_to_marker_presence/marker_

    client_services:
      stop_camera: /parking_camera/get_cam_state

    subscribers:
      raw_frame: /parking_camera/raw_frame

    frames: 
      camera_link: parking_camera_link
      marker_link_prefix: marker_link_

    aruco:
      dict: 5X5_250

    camera_optic_length: 25mm
      
    grid:
      detect_grid: True
      output_id: 20
      grid_ids: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]