aruco_detector:
  ros__parameters:
    camera_module: hal_allied_vision_camera
    pose_topic_hz: 30
    marker_side: 0.25

    custom_marker_side_dict:
      enable: False

    publishers:
      marker_image: /target_tracking/marker_image
      marker_transform_prefix: /target_tracking/camera_to_marker_transform/marker_
      marker_presence_prefix: /target_tracking/camera_to_marker_presence/marker_

    subscribers:
      raw_frame: /parking_camera/raw_frame

    frames: 
      camera_link: parking_camera_link
      marker_link_prefix: marker_link_

    aruco:
      dict: 5X5_100

    camera_optic_length: 8mm
      
    grid:
      detect_grid: True
      number_of_grids: 2
      grid_0:
        output_id: 20
        grid_ids: [0, 1, 2, 3, 4, 5, 6, 7, 8]
        marker_length: 0.07
        marker_separation: 0.04
        rows: 3
        cols: 3
      grid_1:
        output_id: 40
        grid_ids: [30, 31, 32, 33, 34, 35, 36, 37, 38]
        marker_length: 0.084
        marker_separation: 0.012
        rows: 3
        cols: 3